### PR TITLE
Use a custom contract for “apply” to include sequence?* annotation

### PR DESCRIPTION
**Pull request by lexi-lambda**
@AlexKnauth @rfindler This implements a wholly custom contract for `apply`, as recommended in #6. I’ve opted to use a custom contract because I think it’s the only way to use the contract system and get reasonably good error reporting.

Robby, do you have any comments on the implementation of this contract/any ways it could be improved? Do you think this error message is comprehensible?

``` racket
(apply + (vector 1 2 3))
```

```
apply: contract violation
  expected: sequence?, which must be immutable
  given: '#(1 2 3), which is mutable
  in: the last argument of
      (-> procedure? any/c ... sequence? any)
```

Specifically, is it okay to use `->` in the error message with custom syntax? Or is it a no-no to dilute the meaning of the built-in contract operators?

### CODE REVIEW

**Comment by rfindler** [comment]
I don't see any problems with the implementation. 

I think it makes sense to give this combinator its own name and document it and then use that name in the error message to improve discoverability. But if not, then I think you have to pick a syntax that actually would have the same behavior. Would that be something like this?

```
(->* () #:rest (<some-new-list-combinator>) any)
```

?

**Comment by AlexKnauth** [comment]
Re: `give this combinator its own name and document it`:
Well, that's what my pull request does here (https://github.com/lexi-lambda/racket-collections/pull/7). To allow keywords, it uses

``` racket
(kw-hash-> (procedure?) #:rest (list-ending-with sequence?) #:kws any/c any)
```

Which has it's own name and is documented here (http://pkg-build.racket-lang.org/doc/kw-utils/kw-hash_scrbl.html#%28form._%28%28lib._kw-utils%2Fkw-hash%2Fcontract..rkt%29._kw-hash-~3e%29%29). However, the problem with that is most people haven't seen `kw-hash->` before, and they might be confused. If this could reuse the syntax of `->` or `->*`, that would make a better error message that would confuse less people.

**Comment by rfindler** [comment]
I agree that if it could re-use the syntax of -> or ->\* that would be
better, but only if it actually could re-use the syntax with the same
meaning!

Indeed, in that case, I would think that we could improve the -> or ->*
combinator so that it uses your stuff too, in the situation where it is
appropriate. But I'm not clear if there is a way to express what's being
checked using ->\* or not.

**Comment by lexi-lambda** [comment]
I think there are two things at stake here:
1. I want this to have a reasonably good error message if at all possible. Maybe it is misguided, but I think “in the last argument of” is a lot clearer than “in the last element of the rest argument of”.
2. Contract error messages are difficult to understand if the contract syntax displayed in the contract doesn’t match what people expect.

The reason I am reluctant to use your PR, Alex, is that it seems to violate both counts. It _is_ better than using `->*`, given that currently it is impossible to give a correct contract for `apply` using `->*`.

I think that, unfortunately, points 1 and 2 are somewhat in conflict: even if `->*` was updated to allow functions that accept _any_ keyword arguments, the error message would be inferior to a custom contract. However, if it _were_ updated, then at least I could “fake it” by using a custom contract to get the nice error reporting, then presenting the error message in terms of the familiar contract syntax.

I personally value quality of error reporting over familiarity with contract combinators, which is why I lean towards an implementation like this, but it’s also true that there is an untested and perhaps unfounded assumption there that users find those kinds of error messages more helpful. It’s unclear which is better without actually testing how people respond to those kinds of errors.

I think there are a few paths forward right now:
1. Use the implementation I currently have.
2. Update the implementation I currently have to print its error message in terms of `->*` and the `list-ending-with` combinator, even if _technically_ that contract is incorrect because of the keyword arguments.
3. The same as (2), but update `->` or `->*` to support keyword arguments so the contract can actually be correct.

---

For what it’s worth, I think a contract like this:

```
(procedure? any/c ... sequence? . -> . any)
```

...is _far_ clearer than a contract like this:

```
(->* [procedure?] #:rest (list-ending-with sequence?) any)
```

Even if `list-ending-with` were documented, I have a much harder time visually parsing that second contract. I think this is partially due to the fact that Scribble documentation does _not_ document functions in terms of `#:rest` list contracts, but by using `...` and `...+` with individual arguments. Not only is this more intuitive, given that I would guess users imagine variadic functions as taking many optional arguments, not a list of final arguments, but it is also more familiar, since people read the docs constantly but probably look at the more complex contract syntax a lot less.

Ideally, I would like a contract syntax that matches my first example as closely as possible, rather than a contract syntax like `->*` already provides.

**Comment by rfindler** [comment]
I think it would be a reasonable thing to have it be the case that when ->
sees ... in its argument, that it becomes syntactically equivalent to the
->\* written below (but only in the case that the test is made with a
syntactic check on the ... that comes from racket/base).

**Comment by lexi-lambda** [comment]
I’ve been thinking about how easy it would be to add that to `->`, and while I agree it’s a good idea, I don’t think I have the time to implement it right now (it would need to handle things like `(-> procedure? integer? ... string? any/c)`, too). Given that, if implemented, I wouldn’t be able to use it anyway (I currently support versions 6.2 and up), I think I’ll merge this in, and if anyone even so much as mentions it, I can take a look at this once again.

I still think it would be great to have this kind of syntax in Racket itself, but it’s an edge case, so while I may attempt it at some point, it’s not something I want to invest the time into right now. If you wanted to take a crack at it, Alex, it’d be appreciated, but obviously I think it’s okay enough as-is.

Thanks for your feedback and your time, both of you.

**Pull request merged**
