### PR TITLE
Include the mutability annotation for apply on mutable sequences

### LINKED ISSUE #5: Generic apply doesn’t properly warn about mutability in contract violations
This should error with the usual `sequence?*` contract warning about mutability.

``` racket
(apply + (vector 1 2 3))
```

```
apply: contract violation
  expected: sequence?
  given: #<procedure:+>
  argument position: 1st
  other arguments...:
   '#(1 2 3)
```

### PR DESCRIPTION
**Pull request by lexi-lambda**
fixes #5

### CODE REVIEW

**Comment by lexi-lambda** [comment]
@AlexKnauth This is my solution to that particular problem. Care to take a look?

I initially tried doing this through an actual function contract—I went through the trouble of creating a `list-ending-with` contract and using that with a rest argument. Unfortunately, I realized that all that work was wasted, because no function contracts can accept all keyword arguments, and besides, the error message wasn’t very good, anyway.

What I’d really like to be able to do is manually invoke the `sequence?` projection from within `apply`, but I don’t have a blame object, so I can’t do much about that. Instead, I’ve done a small hack to get a nice error message (and I think the error message is close to as good as it’s going to get, which I’m happy about).

@rfindler, I think you are the expert on this topic, so if you have any time to take a look at this and give any feedback or advice, it would be much appreciated.

**Comment by AlexKnauth** [comment]
Once upon a time I made a contract combinator for functions that took keyword arguments. I'll see if I can find it.

**Comment by lexi-lambda** [comment]
That _might_ be helpful, though I’ll state that it would need to have _really good_ error reporting to make it superior to this solution, I think. The trouble with specifying `apply` via contracts is that it has a funny signature (any number of keyword arguments, the _last_ argument needs to be a sequence), so most existing contract combinators don’t give very clear or helpful error messages. In this case, checking everything manually seems to provide significantly better error reporting.

On the other hand, if it were possible to get good error reporting using a contract, I’d obviously much prefer that instead of doing all the error checking manually.

**Comment by rfindler** [comment]
I think I need a few more hints. What is going on here?

**Comment by lexi-lambda** [comment]
Ah, yes, let me give you some context. The issue in question is #5, but that doesn’t really describe the issue in full.

This library rejects mutable sequences like mutable vectors, mutable hash tables, mutable sets, etc., but since they print out exactly the same as immutable ones, this has the potential to be incredibly confusing. A contract error claiming that `#(1 2 3)` is not a `sequence?` when typing `#(1 2 3)` produces a sequence is not helpful. To assist with this, `sequence?` is actually not just a predicate; it is a special flat contract that prints out special contract errors on mutable built-ins:

``` racket
> (first (vector 1 2 3))
first: contract violation
  expected: sequence?, which must be immutable
  given: '#(1 2 3), which is mutable
```

You can see [the implementation of this contract here](https://github.com/lexi-lambda/racket-collections/blob/master/data/collection/collection.rkt#L260).

This works great, but it doesn’t help with `apply`. The generic version of apply works with any kind of sequence as the final argument, but it doesn’t have a contract that enforces this because putting a contract on a function like `apply` seems near-impossible with the current function combinators (it can take any keyword arguments, and only the last argument should be contracted). I’m fine with this because my manual error checking for `apply` is likely be be able to provide better error messages than the existing function contracts, anyway.

However, this means that you get the poor error messages when mutable sequences are involved:

``` racket
> (apply + (vector 1 2 3))
apply: contract violation
  expected: sequence?
  given: '#(1 2 3)
```

The change I’ve implemented recreates the nice error message, but it does so without making use of any of the existing contract machinery, so I’m pretty much just duplicating the code. Is there any way I could meaningfully apply the contract to that particular value, given that I don’t have any knowledge of blame parties? Or is this approach sound?

**Comment by rfindler** [comment]
I think you're talking about some other apply than I'm used to, but perhaps
a related one?

I think maybe a good approach would be to make a new contract combinator,
called (for lack of a better name at least) "apply-like-function" that
accepts a contract for that last argument and returns a contract that you
can put on apply. Or maybe just hand-roll the contract yourself. Either
way, use make-chaperone-contract.

This has the advantage that you get the blame tracking that the contract
system helps you with and you can use other aspects of the contract system
for other contracts that might use this one.

Does that seem useful?

**Comment by AlexKnauth** [comment]
I just finished adding rest argument support to my `kw-hash->` contract combinator here (https://github.com/AlexKnauth/kw-utils/blob/master/kw-utils/kw-hash/contract.rkt). If you use that with your `list-ending-with` contract, does that give you a better error message?

**Comment by lexi-lambda** [comment]
@rfindler That would seem to be the only feasible approach using the contract system. Presumably that would involve manually calling out to `chaperone-procedure` in the projection? (And yes, this library exports its own version of `apply` that works like the one from `racket/base` but works with arbitrary sequences.)

**Comment by lexi-lambda** [comment]
@AlexKnauth Do you have any docs for that? I’m not entirely clear how it works just from looking at the source. If you’d like to give it a shot, though, I’ve pushed my branch that includes the `list-ending-with` contract here: https://github.com/lexi-lambda/racket-collections/tree/list-ending-with-contract

**Comment by AlexKnauth** [comment]
The syntax is similar to `->*` except that `#:kws kws/c` is required, optional arguments aren't supported unless you put their contracts in the rest contract, and it doesn't support anything but `any` for the result contract yet.

**Comment by AlexKnauth** [comment]
Ok, I just pushed https://github.com/AlexKnauth/racket-collections/commit/9a4bb175e21c56a21513ba35d3919842099e62b7. The error message I get is:

```
. . apply: contract violation
  expected: sequence?, which must be immutable
  given: '#(1 2 3), which is mutable
  in: the last element of
      the rest argument of
      (kw-hash->
       (procedure?)
       #:rest
       (list-ending-with sequence?)
       #:kws
       any/c
       any)
  contract from: 
      <pkgs>/collections/data/collection/collection.rkt
  blaming: anonymous-module
   (assuming the contract is correct)
  at: <pkgs>/collections/data/collection/collection.rkt:52.3
```

**Comment by lexi-lambda** [comment]
Hmm, that’s not bad! For reference, the error message produced by this pull request looks like this:

``` racket
> (apply + (vector 1 2 3))
apply: contract violation
  expected: sequence?, which must be immutable
  given: '#(1 2 3), which is mutable
  argument position: 2nd
  other arguments...:
   #<procedure:+>
```

I’m not sure which is better, honestly. What I’d _really_ like is for the error message to say “in: the last argument of”, which I think is only going to be possible with a custom contract. The trouble is that a custom contract in an error message doesn’t mean much if a user hasn’t seen the contract before. For example, if the error message looked like this:

```
apply: contract violation
  expected: sequence?, which must be immutable
  given: '#(1 2 3), which is mutable
  in: the last argument of
      (first/last-> procedure? any/c sequence?)
```

The message is still confusing because `first/last->` is a custom contract that a user doesn’t know about.

**Comment by AlexKnauth** [comment]
My start on the docs for `kw-hash->` is here if you're interested.
source: https://github.com/AlexKnauth/kw-utils/commit/f1031347b84bba628f1c7b2bd63f4a9a26d40ac0
built docs: http://pkg-build.racket-lang.org/doc/kw-utils/kw-hash_scrbl.html#%28part._kw-hash_contracts%29

**Comment by rfindler** [comment]
@alexis: right, I think so.

**Comment by lexi-lambda** [comment]
Closed in favor of #8.

**Pull request closed without merging**
