### PR TITLE
conjoin and list-set before Racket 6.3

### PR DESCRIPTION
**Pull request by greghendershott**
conjoin was in unstable/function and list-set in unstable/list until
Racket 6.3. Requiring those will be a harmless no-op for 6.3+, while
allowing <6.3 to work.

### CODE REVIEW

**Comment by greghendershott** [comment]
Well this didn't work as I'd expected.

I'll look at this more later when I have time.

**Comment by AlexKnauth** [comment]
You also need to add "unstable-list-lib" to the deps, right?

**Comment by greghendershott** [comment]
@AlexKnauth Yes, I believe that's why the 6.3 and HEAD jobs are failing. I'll push a commit to add that. There's also [a doc build failure on the 6.2 job](https://travis-ci.org/lexi-lambda/racket-collections/jobs/95182230#L229).

**Comment by AlexKnauth** [comment]
Looks like it's coming from https://github.com/lexi-lambda/racket-collections/blob/master/data/scribblings/collection/reference.scrbl#L229

**Comment by lexi-lambda** [comment]
That `eval:alts`/`eval:check` this is just borked. I tried fixing `eval:check` (and indeed, the change I made to it makes it "work" now), but the value proposition turned out to mostly be useless in practice. It would be really nice to fix `eval:check` to be more useful, but really, that should probably be removed.

**Comment by lexi-lambda** [comment]
Fixed in a15363bf6492f5df21051fd342a9dae79bfe29da.

**Pull request closed without merging**
