### PR TITLE
add find-min, find-max, and first-by

### PR DESCRIPTION
**Pull request by AlexKnauth**
originally https://github.com/lexi-lambda/racket-alexis-collections/pull/9

### CODE REVIEW

**Comment by lexi-lambda** [comment]
Merged as fc516a4c70b01a447d22c04da026c8e0b9a57d2e with the names `find-best`, `find-min`, and `find-max` and a slightly different API. Sorry for taking such a long time to merge this in! Let me know if you have any issues with the current implementation.

**Comment by AlexKnauth** [comment]
So you went with the `sort` order `(find-best seq < #:key getkey)`? I had thought `(find-best < getkey seq)` would be better because it would allow it to be curried more easily.

**Comment by lexi-lambda** [comment]
Theoretically, you are right. This kind of thing has been an element of contention for me with some of the recent functions I’ve added, including `index-of` and `index-where`. I’ve opted to go with the sequence-first argument order for a few reasons:
1. It’s how Racket does it for just about everything. Unfortunately, Racket is inconsistent, too, given that there are functions like `map` and friends that take the operation first (which is obviously a good thing). Almost everywhere else, though, the sequence argument comes first.
2. I don’t actually care for (1) all that much, but I unfortunately already bought into this argument order with things like `nth`, for example. The ship has sailed, and consistency is better than slightly more elegant single functions, I think.
3. Currying in Racket is pretty rare, I think, in part because functions are generally not designed to cooperate with it (unlike Haskell). My advice is: don’t depend on `curry`, depend on fancy-app/afl/curly-fn/srfi-26. Those work with any argument order, which is important given that certain things can’t be curried, anyway (keyword/optional/rest arguments).

I think it’s possible I made a mistake when designing some of the APIs, but I don’t think it’s disastrous, and at the very least it’s thankfully easy to work around. Perhaps something to consider for a `collections2`, if that ever manifests.

**Comment by AlexKnauth** [comment]
Ok that makes sense.

**Pull request closed without merging**
